In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer, Dropout

In [6]:
# caminho para os arquivos
path_x = '../archives/entradas_breast.csv'
path_y = '../archives/saidas_breast.csv'

# lendo os arquivos de entrada e saida
X = pd.read_csv(path_x)
y = pd.read_csv(path_y)

In [3]:
# criando o classificador e adicionando as camadas
classifier = Sequential()
classifier.add(InputLayer(shape=(30,)))
classifier.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classifier.add(Dropout(0.2))
classifier.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classifier.add(Dropout(0.2))
classifier.add(Dense(units=1, activation='sigmoid'))

2026-02-03 17:57:28.875737: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [4]:
# compilando
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [7]:
# treinando o modelo
classifier.fit(X, y, batch_size=10, epochs=100)

Epoch 1/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.5712 - loss: 1.1635
Epoch 2/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6098 - loss: 0.6386
Epoch 3/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6661 - loss: 0.5742
Epoch 4/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6696 - loss: 0.5252
Epoch 5/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7135 - loss: 0.4866
Epoch 6/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7610 - loss: 0.4838
Epoch 7/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7891 - loss: 0.4599
Epoch 8/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8155 - loss: 0.4217
Epoch 9/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8207 - loss: 0.4239
Epoch 10/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8366 - loss: 0.4172
Epoch 11/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8313 - loss: 0.3978
Epoch 12/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8541 - loss: 0.3687
Epoch 13/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8629 - loss: 0.3635
Epoch 14/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8576 - loss: 0.3722
Epoch 15/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8594 - loss: 0.3626
Epoch 16/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8699 - loss: 0.3448
Epoch 17/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8946 - loss: 0.3165
Epoch 18/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8805 - loss: 0.3029
Epoch 19/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9051 - loss: 0.2819
Epoch 20/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8928 - loss: 0.2898
Epoch 21/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8858 - loss: 0.2979
Epoch 22/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9069 - loss: 0.2640
Epoch 23/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8946 - loss: 0.2832
Epoch 24/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8928 - loss: 0.2688
Epoch 25/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8858 - loss: 0.2731
Epoch 26/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9139 - loss: 0.2473
Epoch 27/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9139 - loss: 0.2540
Epoch 28/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8946 - loss: 0.2483
Epoch 29/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8840 - loss: 0.2861
Epoch 30/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8875 - loss: 0.2540
Epoch 31/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9051 - loss: 0.2552
Epoch 32/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9139 - loss: 0.2300
Epoch 33/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9192 - loss: 0.2356
Epoch 34/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9086 - loss: 0.2296
Epoch 35/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9069 - loss: 0.2564
Epoch 36/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9121 - loss: 0.2330
Epoch 37/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9051 - loss: 0.2369
Epoch 38/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9033 - loss: 0.2215
Epoch 39/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9139 - loss: 0.2232
Epoch 40/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9121 - loss: 0.2266
Epoch 41/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9209 - loss: 0.2136
Epoch 42/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9051 - loss: 0.2251
Epoch 43/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8998 - loss: 0.2473
Epoch 44/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9104 - loss: 0.2173
Epoch 45/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9227 - loss: 0.2249
Epoch 46/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9121 - loss: 0.2172
Epoch 47/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9104 - loss: 0.2279
Epoch 48/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9297 - loss: 0.1920
Epoch 49/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8998 - loss: 0.2330
Epoch 50/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9367 - loss: 0.1939
Epoch 51/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9262 - loss: 0.2022
Epoch 52/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8998 - loss: 0.2336
Epoch 53/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8998 - loss: 0.2332
Epoch 54/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9297 - loss: 0.2037
Epoch 55/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9367 - loss: 0.1854
Epoch 56/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8928 - loss: 0.2519
Epoch 57/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9033 - loss: 0.2203
Epoch 58/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9227 - loss: 0.2163
Epoch 59/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9156 - loss: 0.1956
Epoch 60/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9016 - loss: 0.2355
Epoch 61/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9016 - loss: 0.2190
Epoch 62/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9069 - loss: 0.2350
Epoch 63/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8840 - loss: 0.2561
Epoch 64/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9156 - loss: 0.2345
Epoch 65/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9227 - loss: 0.2069
Epoch 66/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9244 - loss: 0.2011
Epoch 67/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9156 - loss: 0.2190
Epoch 68/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9051 - loss: 0.2191
Epoch 69/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9156 - loss: 0.2109
Epoch 70/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9279 - loss: 0.2060
Epoch 71/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9156 - loss: 0.2087
Epoch 72/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9350 - loss: 0.1867
Epoch 73/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9227 - loss: 0.2016
Epoch 74/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9104 - loss: 0.2266
Epoch 75/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9156 - loss: 0.2202
Epoch 76/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9174 - loss: 0.2051
Epoch 77/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9227 - loss: 0.2078
Epoch 78/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9315 - loss: 0.2022
Epoch 79/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9297 - loss: 0.2052
Epoch 80/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9315 - loss: 0.1877
Epoch 81/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9086 - loss: 0.2293
Epoch 82/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9279 - loss: 0.1721
Epoch 83/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9227 - loss: 0.2111
Epoch 84/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9104 - loss: 0.2176
Epoch 85/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9332 - loss: 0.2014
Epoch 86/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9069 - loss: 0.2267
Epoch 87/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9332 - loss: 0.1887
Epoch 88/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9192 - loss: 0.2139
Epoch 89/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9051 - loss: 0.2480
Epoch 90/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9297 - loss: 0.1959
Epoch 91/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9086 - loss: 0.2216
Epoch 92/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9262 - loss: 0.1933
Epoch 93/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9139 - loss: 0.2110
Epoch 94/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9332 - loss: 0.1799
Epoch 95/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9227 - loss: 0.1956
Epoch 96/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9455 - loss: 0.1738
Epoch 97/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8981 - loss: 0.2366
Epoch 98/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9350 - loss: 0.1978
Epoch 99/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9121 - loss: 0.1998
Epoch 100/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9244 - loss: 0.1895

In [8]:
# vendo os dados de entrada
X

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9456.00,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [9]:
# vendo os dados de saida
y

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [20]:
# criando um dado novo
new = np.array([[15.80, 8.34, 118, 900, 0.10, 0.26, 0.08, 0.134, 0.178, 0.20,
                 0.05, 1098, 0.87, 4500, 145.2, 0.005, 0.04, 0.05, 0.015, 0.03,
                 0.007, 23.15, 16.64, 178.5, 2018, 0.14, 0.185, 0.84, 158, 0.363]])

In [21]:
# vendo o tamanho e formato do dado para ver se esta correto
new.size, new.shape

(30, (1, 30))

In [ ]:
# fazendo a previsão
predict = classifier.predict(new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

In [26]:
# vendo o resultado da previsão
predict = predict > 0.5
predict

array([[ True]])

In [28]:
# mostrando o resultado
if predict:
    print('Malígno')
else: 
    print('Benigno')

Malígno

In [30]:
# salvando o modelo treinado
classifier.save('classifier_breast.keras')

In [31]:
# carregando o modelo treinado
new_classifier = tf.keras.models.load_model('classifier_breast.keras')

In [33]:
# vendo se deu certo
new_classifier.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,357 (9.21 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,572 (6.14 KB)