### Dataset

link: https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
import tensorflow as tf
from tensorflow.keras.models import Sequential

2026-02-03 15:58:38.031332: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-02-03 15:58:38.035205: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-02-03 15:58:38.569806: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-03 15:58:39.745565: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-02-03 15:58:39.746800: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

## Dataframe

In [2]:
# caminho para o arquivo de entrada
path_x = 'archives/entradas_breast.csv'

# lendo o dataframe
df_x = pd.read_csv(path_x)
# mostrando o dataframe
df_x

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9456.00,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [3]:
# caminho para o dataset com os resultados finais (se é ou nao cancer)
path_y = 'archives/saidas_breast.csv'

# lendo e mostrando o dataframe
df_y = pd.read_csv(path_y)
df_y

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

## Train/test Split

In [4]:
# Separando os dados entre treino e teste
X_train, X_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.25)

In [5]:
# vendo a quantidade de linhas e colunas do treino e do teste dos parametros e da resposta
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(426, 30)
(426, 1)
(143, 30)
(143, 1)

## Criando a rede neural

In [6]:
# criando uma rede neural com o tensor flow camada por camada
neural = Sequential([tf.keras.layers.InputLayer(shape=(30,)), # camada de entrada, com 30 dados de entrada
                     tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'), # Camada oculta, com 16 neuronios, com a função de ativação relu, e utilizando de pesos aleatórios
                     tf.keras.layers.Dense(units=16, activation='relu', kernel_initializer='random_uniform'), # Criando agora uma outra camada oculta
                     tf.keras.layers.Dense(units=1, activation='sigmoid') # Camada de saída, com uma unica saída, função sigmoid pois a resposta tem de ser binária
                     ])

2026-02-03 15:58:40.337864: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [7]:
# ver os dados da rede neural
neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

## Configurando a rede neural

In [8]:
# criando agora um optimizador para a rede neural
optimizer = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

In [9]:
# definindo alguns parametros da rede neural
# optimizer é o algoritmo de reajuste dos pesos
# loss é para definidar a função que vai calcular o erro
# metrics são as metricas que serao retornadas com a rede neural
neural.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['binary_accuracy'])

## Treinando

In [10]:
# trainando a rede neural
neural.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.6244 - loss: 0.6461
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7441 - loss: 0.4586
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7911 - loss: 0.4535
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7653 - loss: 0.5098
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8005 - loss: 0.4279
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8310 - loss: 0.3778
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.3873
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8028 - loss: 0.4434
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.4477
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.3557
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.3938
Epoch 12/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.3600
Epoch 13/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 0.4646
Epoch 14/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.4988
Epoch 15/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.4978
Epoch 16/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8310 - loss: 0.4198
Epoch 17/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8709 - loss: 0.3727
Epoch 18/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8873 - loss: 0.3584
Epoch 19/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 0.4023
Epoch 20/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.3855
Epoch 21/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8427 - loss: 0.4985
Epoch 22/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8967 - loss: 0.3546
Epoch 23/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.3768
Epoch 24/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.4235
Epoch 25/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8474 - loss: 0.4286
Epoch 26/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.4837
Epoch 27/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8216 - loss: 0.4625
Epoch 28/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.4182
Epoch 29/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8709 - loss: 0.4042
Epoch 30/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.5029
Epoch 31/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.3977
Epoch 32/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8286 - loss: 0.8619
Epoch 33/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.4200
Epoch 34/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8263 - loss: 0.5367
Epoch 35/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8427 - loss: 0.6419
Epoch 36/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8709 - loss: 0.4212
Epoch 37/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8498 - loss: 0.4486
Epoch 38/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.4390
Epoch 39/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8427 - loss: 0.6382
Epoch 40/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.4622
Epoch 41/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.6731
Epoch 42/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.6636
Epoch 43/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.4138
Epoch 44/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8263 - loss: 0.5433
Epoch 45/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.5596
Epoch 46/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.4128
Epoch 47/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.3977
Epoch 48/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.8830
Epoch 49/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.4219
Epoch 50/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8099 - loss: 0.8004
Epoch 51/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.6797
Epoch 52/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8216 - loss: 0.7716
Epoch 53/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8216 - loss: 0.6857
Epoch 54/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.7002
Epoch 55/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.4983
Epoch 56/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.5809
Epoch 57/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8169 - loss: 0.6028
Epoch 58/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8521 - loss: 0.5407
Epoch 59/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8826 - loss: 0.4953
Epoch 60/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8756 - loss: 0.4620
Epoch 61/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.6633
Epoch 62/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.7145
Epoch 63/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.6159
Epoch 64/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.6205
Epoch 65/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.5419
Epoch 66/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.6379
Epoch 67/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 0.5977
Epoch 68/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8169 - loss: 0.9834
Epoch 69/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 0.7534
Epoch 70/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8192 - loss: 1.3810
Epoch 71/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.7185
Epoch 72/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 1.0158
Epoch 73/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8263 - loss: 0.7035
Epoch 74/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.5519
Epoch 75/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.9836
Epoch 76/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8709 - loss: 0.6249
Epoch 77/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8192 - loss: 0.8348
Epoch 78/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8075 - loss: 1.0150
Epoch 79/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.5836
Epoch 80/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8169 - loss: 0.7926
Epoch 81/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.8357
Epoch 82/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8615 - loss: 0.6188
Epoch 83/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.6988
Epoch 84/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.6039
Epoch 85/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.7153
Epoch 86/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.9994
Epoch 87/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.8039
Epoch 88/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.8434
Epoch 89/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7770 - loss: 1.9877
Epoch 90/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.9982
Epoch 91/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 0.7680
Epoch 92/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 1.2177
Epoch 93/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 1.9036
Epoch 94/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7958 - loss: 1.8384
Epoch 95/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 1.6412
Epoch 96/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7582 - loss: 1.8702
Epoch 97/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8146 - loss: 1.1033
Epoch 98/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8075 - loss: 1.2784
Epoch 99/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7981 - loss: 1.2926
Epoch 100/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7559 - loss: 2.6551

## Vendo os pesos da rede neural

In [ ]:
# pesos da primeira camada
weight_0 = neural.layers[0].get_weights()
weight_0

[array([[ 1.27550215e-01,  2.85868376e-01,  4.00118500e-01,
          3.39975625e-01,  1.56091511e-01, -3.86198848e-01,
          1.00747578e-01, -7.36059248e-02, -3.54947329e-01,
         -5.34876108e-01, -1.94279943e-02, -3.60564172e-01,
         -1.61420748e-01, -1.26747161e-01,  1.22687317e-01,
          1.41470343e-01],
        [-3.07237580e-02,  1.14581063e-01,  3.08991969e-01,
          4.12303060e-01,  1.77259564e-01, -3.94290388e-01,
          1.10650495e-01, -1.16716940e-02, -3.08078468e-01,
         -2.27516085e-01, -9.84065160e-02, -3.45603347e-01,
         -3.41202557e-01, -9.43582878e-02,  1.56098247e-01,
          1.53200984e-01],
        [ 6.35058805e-02,  2.51805801e-02,  3.39941531e-01,
          1.44153237e-01,  9.44715589e-02, -1.11231998e-01,
          6.42021522e-02, -7.84344375e-02,  1.48600461e-02,
         -1.59671620e-01,  2.34322734e-02, -8.97871926e-02,
         -1.44619331e-01, -2.24577244e-02, -9.13863555e-02,
         -7.72879422e-02],
        [ 1.00974642e-01,  5.25452718e-02,  1.24425702e-01,
          2.12737806e-02,  1.38671249e-01,  4.73747887e-02,
         -9.58115608e-03,  3.90018001e-02, -3.78049142e-03,
          2.33032495e-01, -1.87203418e-02,  5.34212142e-02,
          3.45684029e-02,  2.61309389e-02, -6.08305149e-02,
         -7.17145577e-02],
        [-3.44299152e-02,  1.70881391e-01,  1.40434071e-01,
          1.95841235e-03,  9.90530752e-05, -1.42562194e-02,
          6.73889443e-02,  7.98760429e-02, -4.84997686e-03,
         -4.74509031e-01, -4.66082841e-02,  4.24666032e-02,
         -2.45738626e-01, -7.87093565e-02,  1.90654337e-01,
          2.72707939e-01],
        [ 7.62807801e-02,  1.87556878e-01,  3.77786964e-01,
          8.65932181e-02,  4.54246486e-03, -2.39446580e-01,
          1.60548776e-01, -6.19012080e-02, -1.85661420e-01,
         -3.31594110e-01, -2.60420833e-02, -6.58116937e-02,
          1.67026550e-01, -2.76152901e-02,  1.02861844e-01,
         -1.27998635e-01],
        [-4.38941047e-02,  6.16143458e-02,  4.95373048e-02,
         -3.86403427e-02,  2.20965408e-02, -1.39737785e-01,
          1.61975235e-01,  7.68713281e-02, -8.43390524e-02,
         -9.16899502e-01, -4.47533876e-02, -2.63742842e-02,
         -2.43842900e-01, -1.21430881e-01,  1.06370628e-01,
          1.45902276e-01],
        [ 2.74870783e-01,  2.03211784e-01,  3.54039699e-01,
         -6.78662434e-02,  2.79690593e-01, -2.41975278e-01,
          5.67260832e-02,  7.07073789e-03, -2.48556152e-01,
         -3.61944109e-01, -8.25958103e-02, -1.69079065e-01,
          7.04075620e-02, -3.16473484e-01, -4.49633449e-02,
          1.23848375e-02],
        [-3.19636911e-02, -1.05027817e-01, -1.33548558e-01,
         -3.04075107e-02, -1.30877674e-01,  2.54534222e-02,
         -1.45479560e-01,  1.89745557e-02,  1.21899612e-01,
          3.88579369e-01,  1.60091836e-02, -7.86155812e-04,
          6.12769797e-02, -1.21264711e-01, -1.12525605e-01,
          1.80544071e-02],
        [-2.84315825e-01,  2.77648926e-01,  7.39854053e-02,
          3.80878061e-01, -4.24573958e-01,  1.34050250e-01,
         -8.68946239e-02, -2.02214807e-01,  2.43358061e-01,
          2.54107386e-01,  1.03807218e-01,  2.42840007e-01,
          3.11338514e-01,  1.33829236e-01, -3.77072871e-01,
         -3.53394181e-01],
        [-3.44202518e-02,  1.38983443e-01,  2.72100538e-01,
          5.13192341e-02,  2.18782248e-03, -3.93774025e-02,
         -3.80971357e-02, -7.41759241e-02, -1.15043856e-01,
         -1.85636766e-02, -9.04117674e-02, -5.74638732e-02,
         -1.06287703e-01, -1.12520710e-01, -9.70321056e-03,
          5.21255145e-03],
        [ 8.07257295e-02,  2.04761446e-01,  1.57572418e-01,
          2.70262044e-02, -4.31686193e-02, -5.73874414e-02,
         -1.96703859e-02, -1.53495401e-01, -7.12884218e-02,
         -1.55164763e-01, -3.99636365e-02, -4.29323912e-02,
          2.43286595e-01, -1.11800484e-01, -3.47052068e-02,
         -6.53227195e-02],
        [ 4.72097620e-02, -1.79200713e-02, -7.46405637e-03,
          2.94519160e-02,  5.44529408e-02,  7.75777325e-02,
          2.54638083e-02,  8.96934718e-02,  1.17199518e-01,
         -6.53479278e-01,  1.89326536e-02,  6.18073046e-02,
          7.76784047e-02,  9.44544524e-02,  1.82991326e-02,
          2.99257040e-02],
        [ 4.12258834e-01,  1.04161322e+00,  1.07062936e+00,
          5.27306139e-01,  5.87535143e-01, -9.90836263e-01,
          6.78460658e-01,  1.82937548e-01, -9.24457788e-01,
         -5.71816325e-01, -2.38172710e-01, -9.07507658e-01,
         -8.68352294e-01, -3.61435503e-01,  4.11187530e-01,
          5.42602181e-01],
        [-2.39154726e-01,  7.97786787e-02,  4.53837395e-01,
          3.52697045e-01,  1.12585180e-01, -2.77589679e-01,
          1.21035919e-01, -4.77762632e-02, -1.89747736e-01,
         -4.18132752e-01,  4.72594313e-02, -1.83651611e-01,
         -4.17173982e-01,  9.25466791e-02,  2.16594085e-01,
          6.27935380e-02],
        [ 3.21640104e-01,  4.68812317e-01,  2.83354491e-01,
          2.62694925e-01,  1.19498670e-01, -2.99404144e-01,
          1.68633744e-01, -1.85858477e-02, -2.22676963e-01,
         -3.77789557e-01, -1.70817189e-02, -1.83316201e-01,
          7.17378780e-02, -2.82323122e-01,  4.79291260e-01,
          2.80616760e-01],
        [-9.24842060e-02,  2.88630724e-01,  1.59354180e-01,
         -1.84312388e-02, -4.29015368e-01,  3.11549678e-02,
          3.88272181e-02, -1.61122575e-01, -1.02056704e-01,
         -7.60823041e-02, -6.27130643e-02,  3.70516442e-02,
          5.29153645e-01, -1.64055511e-01,  2.60020822e-01,
          8.96055102e-02],
        [-1.84825748e-01, -1.23332344e-01,  1.02076545e-01,
         -1.54124796e-01, -3.91902357e-01,  2.32500494e-01,
         -8.37391764e-02, -8.98061842e-02,  1.62807018e-01,
         -6.29348695e-01,  3.43126804e-02,  1.67438209e-01,
          4.77617264e-01,  1.87400773e-01,  1.82913065e-01,
         -3.46910298e-01],
        [-1.89057276e-01,  1.27893325e-03,  1.99341953e-01,
          2.79828668e-01,  1.12103283e-01,  4.40573022e-02,
          5.90099171e-02, -1.00200556e-01, -1.64033771e-02,
         -3.73394936e-01,  6.21576980e-02,  4.46418896e-02,
         -2.81624526e-01,  1.94824323e-01,  1.32469088e-01,
         -5.40432520e-02],
        [ 8.63973051e-02, -3.14984232e-01, -1.20145686e-01,
         -5.92007041e-02,  3.81420463e-01, -8.98536518e-02,
          1.46332577e-01,  2.07492664e-01, -2.28581782e-02,
         -2.11414725e-01, -3.70948873e-02, -6.53304830e-02,
         -5.19201159e-01, -2.13355079e-01,  5.79961240e-01,
          4.94003832e-01],
        [ 1.39999196e-01,  3.72093827e-01,  4.96321917e-01,
          3.58119041e-01,  2.13420019e-01, -4.65234280e-01,
          1.94472939e-01, -5.17524071e-02, -4.21297073e-01,
         -5.55200219e-01, -5.36424555e-02, -4.48620558e-01,
         -2.95189857e-01, -1.95197180e-01,  2.27967992e-01,
          2.54463822e-01],
        [-7.99141005e-02,  4.73420769e-02,  2.58588433e-01,
          3.12569082e-01,  1.85400352e-01, -3.35312277e-01,
          1.48935318e-01, -2.19804049e-02, -3.43768209e-01,
         -2.85972178e-01, -5.00668399e-02, -3.27081144e-01,
         -4.31641012e-01, -1.07874081e-01,  1.51498780e-01,
          2.47070089e-01],
        [ 4.08592485e-02,  7.64152333e-02,  2.97609329e-01,
          5.85777983e-02,  1.12800233e-01, -1.51282713e-01,
          4.71822433e-02, -9.59633887e-02, -1.93035919e-02,
         -1.55570909e-01, -7.14886636e-02, -7.97132626e-02,
         -1.02806367e-01, -1.35326266e-01, -8.27786624e-02,
         -6.41898811e-02],
        [ 9.12853032e-02,  9.46043730e-02,  1.19959779e-01,
          4.49658968e-02,  1.67510480e-01, -4.37682681e-02,
          3.60353291e-02,  9.39705968e-02, -5.55904508e-02,
          2.09057629e-01, -9.73298997e-02, -5.84395379e-02,
         -4.61353622e-02,  8.99984036e-03,  4.89792414e-02,
          3.40161379e-03],
        [-1.39290154e-01,  1.46232801e-03,  1.35007888e-01,
          3.81569937e-02,  1.10962309e-01, -1.53407693e-01,
         -7.31059387e-02,  1.29949853e-01, -3.25122923e-02,
         -3.52957807e-02,  1.43721662e-02, -7.27828592e-02,
         -4.11439896e-01,  7.58705754e-03, -4.71444987e-02,
         -4.74858694e-02],
        [ 1.34530030e-02, -8.19891505e-03,  2.73458450e-03,
         -8.63098055e-02, -4.66600992e-03, -3.01359557e-02,
         -1.91297662e-02, -7.62557262e-04, -1.33825373e-02,
         -7.41141737e-01, -1.47939986e-02,  2.08430202e-03,
         -2.64159851e-02, -1.82783216e-01, -8.82636681e-02,
         -2.88424436e-02],
        [ 9.68370959e-02,  9.05781314e-02, -8.77906531e-02,
         -1.52727440e-01, -4.99348827e-02, -1.30707145e-01,
         -9.47252214e-02, -7.37918019e-02, -5.87959923e-02,
          3.15202922e-01,  2.05590725e-02, -2.59844214e-02,
          6.55339137e-02, -9.26538184e-02, -2.32437879e-01,
         -1.17026009e-02],
        [ 2.17905670e-01,  1.38472170e-01,  4.23276663e-01,
         -1.57355946e-02,  1.33881062e-01, -3.16072226e-01,
         -2.98674498e-02, -2.49397364e-02, -2.91936696e-01,
         -7.36182630e-02, -1.51524484e-01, -7.82813430e-02,
         -5.48131205e-02, -2.89442867e-01, -9.49537084e-02,
          1.83891848e-01],
        [-1.49200382e-02,  1.66412294e-01,  1.50376409e-01,
          3.95594025e-03, -9.34050791e-03, -3.96678858e-02,
         -8.74557346e-02, -1.37260675e-01, -4.69897278e-02,
         -4.72840756e-01,  2.31530778e-02, -9.33174938e-02,
         -1.12728424e-01, -1.91081539e-02, -5.48385419e-02,
         -5.14735132e-02],
        [-1.44208148e-01,  5.34964167e-02,  2.25085825e-01,
          1.32501051e-01, -6.75245523e-02,  1.49524897e-01,
          2.10671514e-01,  2.64589012e-01,  6.64501861e-02,
         -4.41212840e-02, -7.42686540e-02,  5.05868420e-02,
         -3.79727453e-01, -5.95178343e-02,  3.02101254e-01,
          2.04883248e-01]], dtype=float32),
 array([-0.37315556, -0.07588891,  0.2148181 ,  0.3815242 , -0.29247254,
         0.06968438, -0.14680974, -0.17360935,  0.11420608, -0.31406918,
         0.06991049,  0.06369466,  0.08563891,  0.2278226 , -0.25566012,
        -0.32217875], dtype=float32)]

In [ ]:
# quantidade de listas de pesos da primeira camada
len(weight_0)

2

In [ ]:
# quantidade de pesos da primeira lista da primeira camada
len(weight_0[0])

30

In [ ]:
# quantidade de pesos da segunda lista da primeira camada
len(weight_0[1])

16

### Vendo os pesos das camadas 2 e 3

In [ ]:
weight_1 = neural.layers[1].get_weights()
weight_1

[array([[ 0.09203149, -0.0452299 ,  0.0405011 , -0.0653765 ,  0.310354  ,
         -0.06081918,  0.00702704,  0.0234648 , -0.01467396,  0.10519381,
          0.10075789,  0.00298983,  0.00327627, -0.03629496, -0.02581477,
          0.00476542],
        [ 0.19105704,  0.0354661 ,  0.05887093,  0.04563697,  0.20221096,
         -0.04866806,  0.15429373,  0.03039552, -0.08900876,  0.06847197,
         -0.07495191,  0.05761787, -0.13309246, -0.11468512,  0.00148153,
         -0.07207397],
        [ 0.03797425, -0.08786724, -0.05436535,  0.06240042, -0.01175696,
          0.00870656,  0.0691181 ,  0.10707983, -0.05366859, -0.06632548,
         -0.32656854, -0.02511654, -0.07335734, -0.03844662, -0.01765312,
         -0.04730432],
        [-0.11233187, -0.17622636, -0.14243571,  0.25067648, -0.3166728 ,
          0.01732863,  0.14522767, -0.1386435 , -0.00792958, -0.15222684,
         -0.20147692, -0.23086157, -0.14070927,  0.04393402, -0.01337582,
          0.02398429],
        [ 0.20321757,  0.01265512, -0.0371738 , -0.02335108,  0.26628435,
         -0.00297418,  0.01636671, -0.04927464, -0.08097142,  0.0656354 ,
          0.0806152 ,  0.02093676,  0.03636983, -0.09637924,  0.00898243,
         -0.06139123],
        [ 0.15683797,  0.09992603,  0.11690308, -0.05112625,  0.35219985,
         -0.03396138, -0.03886574, -0.03192808, -0.07589626,  0.06213395,
          0.15470171,  0.05419317,  0.18615028, -0.04422091, -0.06006902,
         -0.02120358],
        [-0.00330473, -0.02675766, -0.08080695,  0.15297793,  0.08096232,
         -0.05145199,  0.06272507, -0.00293956, -0.05489372, -0.022471  ,
          0.08501568, -0.00795985, -0.06546837,  0.01879607,  0.00379539,
         -0.00481479],
        [-0.00757571,  0.0631905 ,  0.02516108,  0.18507217,  0.05497741,
          0.02099342,  0.15119039,  0.00475639, -0.00406738,  0.01370505,
          0.03494127,  0.01151967,  0.13344005, -0.00418944, -0.03556924,
          0.03427297],
        [ 0.17461447,  0.13262202,  0.10770177, -0.1005581 ,  0.28030446,
          0.00239505, -0.09961408, -0.11999705, -0.01357994,  0.12951529,
          0.12018327,  0.10451592,  0.2439827 ,  0.10384344, -0.01263551,
          0.01209978],
        [ 0.11086903,  0.12793991,  0.23154457, -0.00223529,  0.33903474,
         -0.0159069 , -0.06947291, -0.06712416,  0.01429944,  0.08308243,
          0.09503023,  0.13527542,  0.17809244,  0.08069792, -0.03097133,
         -0.00651833],
        [ 0.12890397,  0.09774134,  0.04838334,  0.02473584,  0.23582585,
         -0.0661185 , -0.02608873,  0.01780367, -0.05335407,  0.13986212,
          0.17446776,  0.05184175, -0.03477029,  0.03347827, -0.00178783,
         -0.02934034],
        [ 0.14897403,  0.1045889 ,  0.06691933, -0.04598879,  0.31802183,
         -0.03286767, -0.10165299, -0.07455128, -0.03153767,  0.10825942,
          0.1191977 ,  0.13874553,  0.17908017,  0.01647693, -0.02464028,
         -0.02935544],
        [ 0.13325165,  0.09850831,  0.17535736, -0.04091284,  0.3918135 ,
         -0.00699779,  0.07419059, -0.12166897,  0.01005327,  0.04970874,
          0.07411189,  0.12173349, -0.04250262, -0.03442954, -0.01554357,
         -0.02107222],
        [ 0.06663747,  0.06770752, -0.09515485,  0.19470096,  0.1737585 ,
         -0.0948763 ,  0.14415659, -0.17079294, -0.03160244, -0.1069056 ,
          0.05228028, -0.13585095,  0.04335163,  0.03489612,  0.03483533,
         -0.05320689],
        [ 0.31844476, -0.26913983, -0.31868044, -0.03515695,  0.40146512,
         -0.00997359, -0.04134402, -0.14642335, -0.01476938,  0.29889792,
          0.39823467, -0.3029867 , -0.26161686, -0.13453905, -0.04140528,
          0.04337663],
        [ 0.14513841, -0.08368858, -0.17531927,  0.08696954,  0.40453354,
         -0.00875643, -0.00273714, -0.03552532, -0.00563149,  0.10546092,
          0.32302096, -0.19253697, -0.0853731 , -0.02059857,  0.03031709,
          0.05442216]], dtype=float32),
 array([-0.40742975,  0.27569017,  0.21393101,  0.2883716 , -0.4281866 ,
        -0.0642337 ,  0.33726907,  0.0502488 , -0.03853843, -0.40889844,
        -0.34475002,  0.24271627,  0.17288373, -0.02345869, -0.009751  ,
        -0.12294706], dtype=float32)]

In [17]:
weight_2 = neural.layers[2].get_weights()
weight_2

[array([[-0.13805135],
        [ 0.31072548],
        [ 0.32401747],
        [ 0.1737607 ],
        [-0.07162839],
        [-0.31618017],
        [ 0.25559002],
        [-0.44483083],
        [-0.328848  ],
        [-0.17730612],
        [-0.07154596],
        [ 0.24689041],
        [ 0.38835832],
        [ 0.06802619],
        [ 0.2790125 ],
        [-0.3928339 ]], dtype=float32),
 array([0.35473147], dtype=float32)]

## Verificando as previsões, acurácia e erro

In [11]:
# fazendo as previsoes de teste
predict = neural.predict(X_test)
predict = predict > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

In [12]:
# vendo a precisão do modelo
accuracy_score(y_test, predict)

0.7552447552447552

In [13]:
# vendo a matriz de confusão
confusion_matrix(y_test, predict)

array([[18, 28],
       [ 7, 90]])

In [14]:
# vendo o valor do erro e da accuracy com o metodo da rede neural
neural.evaluate(X_test, y_test)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.7552 - loss: 1.7388

[1.7387690544128418, 0.7552447319030762]