In [40]:
import pandas as pd
import tensorflow as tf
import sklearn
import scikeras

from scikeras.wrappers import KerasRegressor
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler

In [41]:
# caminho para o csv
path = 'kc_house_data.csv'

# lendo o csv
df = pd.read_csv(path)
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [42]:
# tirando colunas que eu julgo desnecessárias
df.drop('id', axis=1, inplace=True)
df.drop('date', axis=1, inplace=True)
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [43]:
# vendo se há valores nulos
df.isnull().sum()

price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [44]:
# separando o X do Y
X = df.iloc[:, 1:19]
y = df.iloc[:, 0]

In [45]:
# fazendo a transformação dos valores
# O zipcode irá virar varias colunas (tratado como valor categorico)
# para os outros valores, eles serão todos padronizados
OneHotEncoder = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), ['zipcode']),], remainder=MinMaxScaler())
X = OneHotEncoder.fit_transform(X)

In [46]:
# vendo os formatos
X.shape, y.shape

((21613, 87), (21613,))

In [47]:
# função para criar a rede neural
def create_network():
    k.clear_session()
    # rede neural
    neural_network = Sequential([
        tf.keras.layers.InputLayer(shape=(87,)),
        tf.keras.layers.Dense(units=44, activation='relu'),
        tf.keras.layers.Dense(units=44, activation='relu'),
        tf.keras.layers.Dense(units=1, activation='linear'),
    ])
    # compilação
    neural_network.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mean_absolute_error'])
    return neural_network

In [48]:
# fazendo um treinamento simples
neural_network = create_network()
neural_network.fit(X, y, batch_size=50, epochs = 100)

Epoch 1/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 539447.9375 - mean_absolute_error: 539447.9375
Epoch 2/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 529757.4375 - mean_absolute_error: 529757.4375
Epoch 3/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 496569.5938 - mean_absolute_error: 496569.5938
Epoch 4/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 430166.7500 - mean_absolute_error: 430166.7500
Epoch 5/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 327109.4375 - mean_absolute_error: 327109.4062
Epoch 6/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 228131.7188 - mean_absolute_error: 228131.7188
Epoch 7/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 189708.4844 - mean_absolute_error: 189708.4844
Epoch 8/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 179624.3906 - mean_absolute_error: 179624.3906
Epoch 9/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 174923.4531 - mean_absolute_error: 174923.4531
Epoch 10/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 170896.6250 - mean_absolute_error: 170896.6250
Epoch 11/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 166896.1094 - mean_absolute_error: 166896.1094
Epoch 12/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 162811.2031 - mean_absolute_error: 162811.2031
Epoch 13/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 158590.0000 - mean_absolute_error: 158590.0000
Epoch 14/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 154244.0000 - mean_absolute_error: 154244.0000
Epoch 15/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 149761.1719 - mean_absolute_error: 149761.1719
Epoch 16/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 145149.5312 - mean_absolute_error: 145149.5312
Epoch 17/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 140450.1250 - mean_absolute_error: 140450.1250
Epoch 18/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 135718.3594 - mean_absolute_error: 135718.3594
Epoch 19/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 131061.7344 - mean_absolute_error: 131061.7344
Epoch 20/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 126665.2500 - mean_absolute_error: 126665.2500
Epoch 21/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 122700.7266 - mean_absolute_error: 122700.7266
Epoch 22/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 119307.6875 - mean_absolute_error: 119307.6875
Epoch 23/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 116485.6250 - mean_absolute_error: 116485.6250
Epoch 24/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 114144.7656 - mean_absolute_error: 114144.7656
Epoch 25/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 112088.7578 - mean_absolute_error: 112088.7578
Epoch 26/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 110303.3359 - mean_absolute_error: 110303.3359
Epoch 27/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 108777.0234 - mean_absolute_error: 108777.0234
Epoch 28/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 107412.7422 - mean_absolute_error: 107412.7422
Epoch 29/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 106185.1953 - mean_absolute_error: 106185.1953
Epoch 30/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 105056.7109 - mean_absolute_error: 105056.7109
Epoch 31/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 104039.6797 - mean_absolute_error: 104039.6797
Epoch 32/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 103113.7734 - mean_absolute_error: 103113.7734
Epoch 33/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 102265.4922 - mean_absolute_error: 102265.4922
Epoch 34/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 101474.5469 - mean_absolute_error: 101474.5469
Epoch 35/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100750.4453 - mean_absolute_error: 100750.4453
Epoch 36/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 100074.6094 - mean_absolute_error: 100074.6094
Epoch 37/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 99448.9219 - mean_absolute_error: 99448.9219
Epoch 38/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 98874.4453 - mean_absolute_error: 98874.4453
Epoch 39/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 98316.4688 - mean_absolute_error: 98316.4688
Epoch 40/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 97820.6016 - mean_absolute_error: 97820.6172
Epoch 41/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97327.9922 - mean_absolute_error: 97327.9922
Epoch 42/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 96871.1172 - mean_absolute_error: 96871.1172
Epoch 43/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 96446.3828 - mean_absolute_error: 96446.3828
Epoch 44/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 96047.5234 - mean_absolute_error: 96047.5234
Epoch 45/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 95668.7266 - mean_absolute_error: 95668.7266
Epoch 46/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 95327.9531 - mean_absolute_error: 95327.9531
Epoch 47/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 95001.1016 - mean_absolute_error: 95001.1016
Epoch 48/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 94692.5391 - mean_absolute_error: 94692.5391
Epoch 49/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 94407.0469 - mean_absolute_error: 94407.0469
Epoch 50/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 94138.8203 - mean_absolute_error: 94138.8203
Epoch 51/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93891.0938 - mean_absolute_error: 93891.1094
Epoch 52/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93648.2578 - mean_absolute_error: 93648.2578
Epoch 53/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93418.1016 - mean_absolute_error: 93418.1016
Epoch 54/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93201.2891 - mean_absolute_error: 93201.2891
Epoch 55/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92998.0625 - mean_absolute_error: 92998.0625
Epoch 56/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92803.6953 - mean_absolute_error: 92803.6953
Epoch 57/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 92622.6641 - mean_absolute_error: 92622.6562
Epoch 58/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92455.8203 - mean_absolute_error: 92455.8203
Epoch 59/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 92287.2812 - mean_absolute_error: 92287.2812
Epoch 60/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92141.9766 - mean_absolute_error: 92141.9844
Epoch 61/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 91987.2109 - mean_absolute_error: 91987.2109
Epoch 62/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91845.3828 - mean_absolute_error: 91845.3828
Epoch 63/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 91716.7266 - mean_absolute_error: 91716.7266
Epoch 64/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91577.9531 - mean_absolute_error: 91577.9531
Epoch 65/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91451.1250 - mean_absolute_error: 91451.1250
Epoch 66/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91341.9453 - mean_absolute_error: 91341.9453
Epoch 67/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91215.3750 - mean_absolute_error: 91215.3750
Epoch 68/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91120.7734 - mean_absolute_error: 91120.7734
Epoch 69/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 91007.0234 - mean_absolute_error: 91007.0234
Epoch 70/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90900.4297 - mean_absolute_error: 90900.4297
Epoch 71/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 90809.2344 - mean_absolute_error: 90809.2344
Epoch 72/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90705.6719 - mean_absolute_error: 90705.6719
Epoch 73/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 90622.1328 - mean_absolute_error: 90622.1328
Epoch 74/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 90539.3203 - mean_absolute_error: 90539.3203
Epoch 75/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 90466.8594 - mean_absolute_error: 90466.8594
Epoch 76/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90376.6562 - mean_absolute_error: 90376.6562
Epoch 77/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90298.4609 - mean_absolute_error: 90298.4609
Epoch 78/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90220.0234 - mean_absolute_error: 90220.0234
Epoch 79/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 90147.8516 - mean_absolute_error: 90147.8516
Epoch 80/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90083.2109 - mean_absolute_error: 90083.2109
Epoch 81/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90004.1016 - mean_absolute_error: 90004.1016
Epoch 82/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89944.6719 - mean_absolute_error: 89944.6719
Epoch 83/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 89890.0859 - mean_absolute_error: 89890.0859
Epoch 84/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 89821.8594 - mean_absolute_error: 89821.8594
Epoch 85/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89752.8125 - mean_absolute_error: 89752.8125
Epoch 86/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 89690.1641 - mean_absolute_error: 89690.1641
Epoch 87/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89615.3750 - mean_absolute_error: 89615.3750
Epoch 88/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 89549.7578 - mean_absolute_error: 89549.7578
Epoch 89/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89463.8828 - mean_absolute_error: 89463.8828
Epoch 90/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89369.9375 - mean_absolute_error: 89369.9375
Epoch 91/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89271.5312 - mean_absolute_error: 89271.5312
Epoch 92/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 89170.2109 - mean_absolute_error: 89170.2109
Epoch 93/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89051.4062 - mean_absolute_error: 89051.4062
Epoch 94/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 88975.5938 - mean_absolute_error: 88975.5938
Epoch 95/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 88910.7734 - mean_absolute_error: 88910.7734
Epoch 96/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 88851.3359 - mean_absolute_error: 88851.3359
Epoch 97/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 88771.3359 - mean_absolute_error: 88771.3359
Epoch 98/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 88708.2031 - mean_absolute_error: 88708.2031
Epoch 99/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 88639.5078 - mean_absolute_error: 88639.5078
Epoch 100/100
433/433 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 88566.7422 - mean_absolute_error: 88566.7422

In [49]:
# criando o modelo com o keras
neural_network = KerasRegressor(model=create_network, epochs=100, batch_size=50)

In [50]:
# fazendo o treinamento
results = cross_val_score(estimator=neural_network, X=X, y=y, cv=5, scoring='neg_mean_absolute_error')

Epoch 1/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 540052.3750 - mean_absolute_error: 540052.3750
Epoch 2/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 533857.1875 - mean_absolute_error: 533857.1875
Epoch 3/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 511794.0625 - mean_absolute_error: 511794.0625
Epoch 4/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 466078.7812 - mean_absolute_error: 466078.7812
Epoch 5/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 391821.1562 - mean_absolute_error: 391821.1562
Epoch 6/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 292350.3125 - mean_absolute_error: 292350.3438
Epoch 7/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 215707.6406 - mean_absolute_error: 215707.6406
Epoch 8/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 187692.1406 - mean_absolute_error: 187692.1406
Epoch 9/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 179291.4531 - mean_absolute_error: 179291.4531
Epoch 10/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 175224.0156 - mean_absolute_error: 175224.0156
Epoch 11/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 171768.2969 - mean_absolute_error: 171768.2969
Epoch 12/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 168387.7812 - mean_absolute_error: 168387.7812
Epoch 13/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 164967.9688 - mean_absolute_error: 164967.9688
Epoch 14/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 161503.6250 - mean_absolute_error: 161503.6250
Epoch 15/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 157943.8750 - mean_absolute_error: 157943.8750
Epoch 16/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 154312.1250 - mean_absolute_error: 154312.1250
Epoch 17/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 150579.0938 - mean_absolute_error: 150579.0938
Epoch 18/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 146762.2188 - mean_absolute_error: 146762.2188
Epoch 19/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 142864.6875 - mean_absolute_error: 142864.6875
Epoch 20/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 138877.0781 - mean_absolute_error: 138877.0781
Epoch 21/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 134840.0781 - mean_absolute_error: 134840.0781
Epoch 22/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 130837.7344 - mean_absolute_error: 130837.7344
Epoch 23/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 126990.2266 - mean_absolute_error: 126990.2266
Epoch 24/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 123488.4062 - mean_absolute_error: 123488.4062
Epoch 25/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 120420.3828 - mean_absolute_error: 120420.3828
Epoch 26/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 117737.2891 - mean_absolute_error: 117737.2891
Epoch 27/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 115412.1016 - mean_absolute_error: 115412.1016
Epoch 28/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 113394.1484 - mean_absolute_error: 113394.1406
Epoch 29/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 111604.1250 - mean_absolute_error: 111604.1250
Epoch 30/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 110009.8984 - mean_absolute_error: 110009.8984
Epoch 31/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 108621.4844 - mean_absolute_error: 108621.4922
Epoch 32/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 107371.3438 - mean_absolute_error: 107371.3359
Epoch 33/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 106220.0078 - mean_absolute_error: 106220.0078
Epoch 34/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 105174.1484 - mean_absolute_error: 105174.1484
Epoch 35/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 104211.5703 - mean_absolute_error: 104211.5625
Epoch 36/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 103348.0469 - mean_absolute_error: 103348.0469
Epoch 37/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 102533.8672 - mean_absolute_error: 102533.8672
Epoch 38/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 101761.1641 - mean_absolute_error: 101761.1641
Epoch 39/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 101067.6562 - mean_absolute_error: 101067.6562
Epoch 40/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 100398.1719 - mean_absolute_error: 100398.1719
Epoch 41/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99785.5547 - mean_absolute_error: 99785.5547
Epoch 42/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99207.5078 - mean_absolute_error: 99207.5078
Epoch 43/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 98659.6328 - mean_absolute_error: 98659.6328
Epoch 44/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 98147.9531 - mean_absolute_error: 98147.9531
Epoch 45/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97656.9297 - mean_absolute_error: 97656.9297
Epoch 46/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97191.8984 - mean_absolute_error: 97191.8984
Epoch 47/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96753.8203 - mean_absolute_error: 96753.8203
Epoch 48/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96346.1562 - mean_absolute_error: 96346.1562
Epoch 49/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 95960.7422 - mean_absolute_error: 95960.7422
Epoch 50/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 95590.0625 - mean_absolute_error: 95590.0625
Epoch 51/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 95240.6484 - mean_absolute_error: 95240.6484
Epoch 52/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 94916.6875 - mean_absolute_error: 94916.6875
Epoch 53/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 94585.6406 - mean_absolute_error: 94585.6406
Epoch 54/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 94309.0469 - mean_absolute_error: 94309.0469
Epoch 55/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 94042.2188 - mean_absolute_error: 94042.2188
Epoch 56/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 93779.5781 - mean_absolute_error: 93779.5781
Epoch 57/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93523.5781 - mean_absolute_error: 93523.5781
Epoch 58/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93307.0781 - mean_absolute_error: 93307.0781
Epoch 59/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 93084.4531 - mean_absolute_error: 93084.4531
Epoch 60/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92865.1250 - mean_absolute_error: 92865.1250
Epoch 61/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92660.0703 - mean_absolute_error: 92660.0703
Epoch 62/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92461.3672 - mean_absolute_error: 92461.3672
Epoch 63/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92275.1172 - mean_absolute_error: 92275.1172
Epoch 64/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 92084.9844 - mean_absolute_error: 92084.9844
Epoch 65/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91920.1641 - mean_absolute_error: 91920.1641
Epoch 66/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91758.3672 - mean_absolute_error: 91758.3672
Epoch 67/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91614.5703 - mean_absolute_error: 91614.5703
Epoch 68/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91465.4922 - mean_absolute_error: 91465.4922
Epoch 69/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91321.6484 - mean_absolute_error: 91321.6484
Epoch 70/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91196.9922 - mean_absolute_error: 91196.9922
Epoch 71/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91068.4844 - mean_absolute_error: 91068.4844
Epoch 72/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90952.9141 - mean_absolute_error: 90952.9141
Epoch 73/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 90816.4297 - mean_absolute_error: 90816.4297
Epoch 74/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90702.2188 - mean_absolute_error: 90702.2188
Epoch 75/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 90591.0469 - mean_absolute_error: 90591.0469
Epoch 76/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90477.2344 - mean_absolute_error: 90477.2344
Epoch 77/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90362.1719 - mean_absolute_error: 90362.1719
Epoch 78/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90248.7266 - mean_absolute_error: 90248.7266
Epoch 79/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90124.2812 - mean_absolute_error: 90124.2812
Epoch 80/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 89997.7734 - mean_absolute_error: 89997.7734
Epoch 81/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89874.9844 - mean_absolute_error: 89874.9844
Epoch 82/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89742.3438 - mean_absolute_error: 89742.3438
Epoch 83/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89619.6328 - mean_absolute_error: 89619.6328
Epoch 84/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89515.1797 - mean_absolute_error: 89515.1797
Epoch 85/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 89414.3281 - mean_absolute_error: 89414.3359
Epoch 86/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 89314.7500 - mean_absolute_error: 89314.7500
Epoch 87/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 89222.0547 - mean_absolute_error: 89222.0547
Epoch 88/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89139.4844 - mean_absolute_error: 89139.4844
Epoch 89/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 89051.3438 - mean_absolute_error: 89051.3438
Epoch 90/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 88957.6328 - mean_absolute_error: 88957.6328
Epoch 91/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 88889.2656 - mean_absolute_error: 88889.2656
Epoch 92/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 88802.7734 - mean_absolute_error: 88802.7734
Epoch 93/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 88719.3047 - mean_absolute_error: 88719.3047
Epoch 94/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 88637.1328 - mean_absolute_error: 88637.1406
Epoch 95/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 88571.4844 - mean_absolute_error: 88571.4844
Epoch 96/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 88491.3516 - mean_absolute_error: 88491.3516
Epoch 97/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 88415.2969 - mean_absolute_error: 88415.2969
Epoch 98/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 88338.3203 - mean_absolute_error: 88338.3203
Epoch 99/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 88250.7422 - mean_absolute_error: 88250.7422
Epoch 100/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 88163.5234 - mean_absolute_error: 88163.5234
87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Epoch 1/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 542033.2500 - mean_absolute_error: 542033.2500
Epoch 2/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 535860.1250 - mean_absolute_error: 535860.1250
Epoch 3/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 514555.1875 - mean_absolute_error: 514555.1875
Epoch 4/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 471147.9375 - mean_absolute_error: 471147.9375
Epoch 5/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 400978.5625 - mean_absolute_error: 400978.5625
Epoch 6/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 305373.2812 - mean_absolute_error: 305373.2812
Epoch 7/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 224479.6406 - mean_absolute_error: 224479.6406
Epoch 8/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 191617.0781 - mean_absolute_error: 191617.0781
Epoch 9/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 181623.5312 - mean_absolute_error: 181623.5312
Epoch 10/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 177191.2969 - mean_absolute_error: 177191.2969
Epoch 11/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 173697.5156 - mean_absolute_error: 173697.5156
Epoch 12/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 170320.8125 - mean_absolute_error: 170320.8125
Epoch 13/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 166928.2031 - mean_absolute_error: 166928.2188
Epoch 14/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 163485.5938 - mean_absolute_error: 163485.5781
Epoch 15/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 159972.1719 - mean_absolute_error: 159972.1719
Epoch 16/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 156351.9688 - mean_absolute_error: 156351.9688
Epoch 17/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 152633.0156 - mean_absolute_error: 152633.0156
Epoch 18/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 148854.6406 - mean_absolute_error: 148854.6406
Epoch 19/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 144979.0781 - mean_absolute_error: 144979.0781
Epoch 20/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 141017.0000 - mean_absolute_error: 141016.9844
Epoch 21/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 137034.1719 - mean_absolute_error: 137034.1719
Epoch 22/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 133042.9844 - mean_absolute_error: 133042.9844
Epoch 23/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 129155.7734 - mean_absolute_error: 129155.7734
Epoch 24/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 125541.8047 - mean_absolute_error: 125541.8047
Epoch 25/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 122316.9297 - mean_absolute_error: 122316.9297
Epoch 26/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 119517.5625 - mean_absolute_error: 119517.5625
Epoch 27/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 117096.0781 - mean_absolute_error: 117096.0781
Epoch 28/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 115027.3438 - mean_absolute_error: 115027.3438
Epoch 29/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 113199.1016 - mean_absolute_error: 113199.1016
Epoch 30/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 111583.1641 - mean_absolute_error: 111583.1641
Epoch 31/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 110164.2344 - mean_absolute_error: 110164.2344
Epoch 32/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 108899.0391 - mean_absolute_error: 108899.0391
Epoch 33/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 107751.7188 - mean_absolute_error: 107751.7188
Epoch 34/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 106700.1953 - mean_absolute_error: 106700.2031
Epoch 35/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 105716.6016 - mean_absolute_error: 105716.6016
Epoch 36/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 104829.6094 - mean_absolute_error: 104829.6094
Epoch 37/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 104014.3047 - mean_absolute_error: 104014.3047
Epoch 38/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 103258.4062 - mean_absolute_error: 103258.4062
Epoch 39/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 102555.5469 - mean_absolute_error: 102555.5469
Epoch 40/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 101899.8203 - mean_absolute_error: 101899.8203
Epoch 41/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 101274.8047 - mean_absolute_error: 101274.8047
Epoch 42/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 100688.4297 - mean_absolute_error: 100688.4297
Epoch 43/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 100145.3906 - mean_absolute_error: 100145.3906
Epoch 44/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99622.3438 - mean_absolute_error: 99622.3438
Epoch 45/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99135.2578 - mean_absolute_error: 99135.2578
Epoch 46/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 98658.5078 - mean_absolute_error: 98658.5078
Epoch 47/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 98212.2266 - mean_absolute_error: 98212.2266
Epoch 48/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 97783.2266 - mean_absolute_error: 97783.2344
Epoch 49/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 97411.0859 - mean_absolute_error: 97411.0859
Epoch 50/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 97004.2734 - mean_absolute_error: 97004.2578
Epoch 51/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 96639.5078 - mean_absolute_error: 96639.5078
Epoch 52/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 96289.7891 - mean_absolute_error: 96289.7734
Epoch 53/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 95960.4844 - mean_absolute_error: 95960.4844
Epoch 54/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 95654.9141 - mean_absolute_error: 95654.9141
Epoch 55/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 95354.7969 - mean_absolute_error: 95354.7969
Epoch 56/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 95086.3906 - mean_absolute_error: 95086.3906
Epoch 57/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 94812.8281 - mean_absolute_error: 94812.8281
Epoch 58/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 94567.6719 - mean_absolute_error: 94567.6719
Epoch 59/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 94329.4453 - mean_absolute_error: 94329.4453
Epoch 60/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 94103.3203 - mean_absolute_error: 94103.3203
Epoch 61/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 93878.3047 - mean_absolute_error: 93878.3047
Epoch 62/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 93685.7656 - mean_absolute_error: 93685.7656
Epoch 63/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 93488.9453 - mean_absolute_error: 93488.9453
Epoch 64/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 93307.2578 - mean_absolute_error: 93307.2578
Epoch 65/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 93151.2266 - mean_absolute_error: 93151.2266
Epoch 66/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92985.4609 - mean_absolute_error: 92985.4609
Epoch 67/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 92824.1875 - mean_absolute_error: 92824.1875
Epoch 68/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 92680.9688 - mean_absolute_error: 92680.9688
Epoch 69/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 92533.2500 - mean_absolute_error: 92533.2500
Epoch 70/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 92386.5000 - mean_absolute_error: 92386.5000
Epoch 71/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 92253.8672 - mean_absolute_error: 92253.8672
Epoch 72/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 92131.2266 - mean_absolute_error: 92131.2266
Epoch 73/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 92008.2734 - mean_absolute_error: 92008.2734
Epoch 74/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 91887.6172 - mean_absolute_error: 91887.6172
Epoch 75/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 91778.3984 - mean_absolute_error: 91778.3984
Epoch 76/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91664.0703 - mean_absolute_error: 91664.0781
Epoch 77/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91562.1797 - mean_absolute_error: 91562.1797
Epoch 78/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91459.1562 - mean_absolute_error: 91459.1562
Epoch 79/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91339.5469 - mean_absolute_error: 91339.5469
Epoch 80/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91267.6328 - mean_absolute_error: 91267.6328
Epoch 81/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 91170.2500 - mean_absolute_error: 91170.2500
Epoch 82/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91084.3984 - mean_absolute_error: 91084.3984
Epoch 83/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 90996.8359 - mean_absolute_error: 90996.8359
Epoch 84/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 90916.2422 - mean_absolute_error: 90916.2422
Epoch 85/100
346/346 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 90834.1406 - mean_absolute_error: 90834.1406
Epoch 86/100